/**
 * Códigos de error estables para que el cliente pueda ramificar sin parsear mensajes.
 * Patrón sugerido: DOMINIO_ACCION o DOMINIO_RECURSO_MOTIVO.
 */
export const ErrorCode = {
  // Infra / configuración
  CONFIG_DATABASE_URL_MISSING: 'CONFIG_DATABASE_URL_MISSING',

  // Validación genérica (pipe)
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Auth
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_USERNAME_IN_USE: 'AUTH_USERNAME_IN_USE',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_NOT_VERIFIED: 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_VERIFY_TOKEN_INVALID: 'AUTH_VERIFY_TOKEN_INVALID',
  AUTH_VERIFY_TOKEN_EXPIRED: 'AUTH_VERIFY_TOKEN_EXPIRED',

  // Mail
  MAIL_RESEND_NOT_CONFIGURED: 'MAIL_RESEND_NOT_CONFIGURED',
  MAIL_SEND_FAILED: 'MAIL_SEND_FAILED',

  // Usuarios / perfiles
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_USERNAME_INVALID: 'USER_USERNAME_INVALID',
  USER_CANNOT_FOLLOW_SELF: 'USER_CANNOT_FOLLOW_SELF',
  USER_PROFILE_NOTHING_TO_UPDATE: 'USER_PROFILE_NOTHING_TO_UPDATE',
  USER_USERNAME_IN_USE: 'USER_USERNAME_IN_USE',
  USER_PROFILE_IMAGE_TYPE_INVALID: 'USER_PROFILE_IMAGE_TYPE_INVALID',
  USER_INVALID_OPERATION: 'USER_INVALID_OPERATION',

  // Notificaciones
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Challenges
  CHALLENGE_ENDS_AT_NOT_FUTURE: 'CHALLENGE_ENDS_AT_NOT_FUTURE',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  CHALLENGE_MODE_CHANGE_FORBIDDEN: 'CHALLENGE_MODE_CHANGE_FORBIDDEN',
  CHALLENGE_NOTHING_TO_UPDATE: 'CHALLENGE_NOTHING_TO_UPDATE',
  CHALLENGE_WRONG_MODE_USE_TEAMS: 'CHALLENGE_WRONG_MODE_USE_TEAMS',
  CHALLENGE_WRONG_MODE_USE_SOLO_LEAVE: 'CHALLENGE_WRONG_MODE_USE_SOLO_LEAVE',
  CHALLENGE_ALREADY_ENROLLED_SOLO: 'CHALLENGE_ALREADY_ENROLLED_SOLO',
  CHALLENGE_WRONG_MODE_USE_TEAMS_LEAVE: 'CHALLENGE_WRONG_MODE_USE_TEAMS_LEAVE',
  CHALLENGE_SOLO_NOT_ENROLLED: 'CHALLENGE_SOLO_NOT_ENROLLED',
  CHALLENGE_WRONG_MODE_USE_JOIN: 'CHALLENGE_WRONG_MODE_USE_JOIN',
  CHALLENGE_TEAM_MODE_NOT_APPLICABLE: 'CHALLENGE_TEAM_MODE_NOT_APPLICABLE',
  CHALLENGE_TEAM_NOT_FOUND: 'CHALLENGE_TEAM_NOT_FOUND',
  CHALLENGE_TEAM_ALREADY_MEMBER: 'CHALLENGE_TEAM_ALREADY_MEMBER',
  CHALLENGE_WRONG_MODE_USE_SOLO_LEAVE_TEAM: 'CHALLENGE_WRONG_MODE_USE_SOLO_LEAVE_TEAM',
  CHALLENGE_TEAM_NOT_A_MEMBER: 'CHALLENGE_TEAM_NOT_A_MEMBER',
  CHALLENGE_ENDED: 'CHALLENGE_ENDED',
  CHALLENGE_FORBIDDEN_NOT_CREATOR: 'CHALLENGE_FORBIDDEN_NOT_CREATOR',
  CHALLENGE_TEAM_CONFLICT_ALREADY_IN_TEAM: 'CHALLENGE_TEAM_CONFLICT_ALREADY_IN_TEAM',

  // Posts / feed auth
  POST_AUTH_REQUIRED_FOR_FOLLOWING_FEED: 'POST_AUTH_REQUIRED_FOR_FOLLOWING_FEED',
  POST_IMAGE_TYPE_INVALID: 'POST_IMAGE_TYPE_INVALID',
  POST_PUBLISH_TITLE_REQUIRED: 'POST_PUBLISH_TITLE_REQUIRED',
  POST_DRAFT_NOT_FOUND: 'POST_DRAFT_NOT_FOUND',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_COMMENT_EMPTY: 'POST_COMMENT_EMPTY',
  POST_COMMENT_NOT_FOUND: 'POST_COMMENT_NOT_FOUND',
  POST_COMMENT_PARENT_INVALID: 'POST_COMMENT_PARENT_INVALID',
  POST_FORBIDDEN_COMMENT_AUTHOR: 'POST_FORBIDDEN_COMMENT_AUTHOR',
  POST_FORBIDDEN_AUTHOR: 'POST_FORBIDDEN_AUTHOR',
  POST_TITLE_EMPTY: 'POST_TITLE_EMPTY',

  // Discusiones
  DISCUSSION_UNAUTHORIZED_VIEW: 'DISCUSSION_UNAUTHORIZED_VIEW',
  DISCUSSION_AUTH_REQUIRED_FOR_FOLLOWING_FEED: 'DISCUSSION_AUTH_REQUIRED_FOR_FOLLOWING_FEED',
  DISCUSSION_NOT_FOUND: 'DISCUSSION_NOT_FOUND',
  DISCUSSION_FORBIDDEN_EDIT: 'DISCUSSION_FORBIDDEN_EDIT',
  DISCUSSION_TITLE_EMPTY: 'DISCUSSION_TITLE_EMPTY',
  DISCUSSION_NOTHING_TO_UPDATE: 'DISCUSSION_NOTHING_TO_UPDATE',
  DISCUSSION_FORBIDDEN_DELETE: 'DISCUSSION_FORBIDDEN_DELETE',
  DISCUSSION_COMMENT_EMPTY: 'DISCUSSION_COMMENT_EMPTY',
  DISCUSSION_COMMENT_NOT_FOUND: 'DISCUSSION_COMMENT_NOT_FOUND',
  DISCUSSION_COMMENT_PARENT_INVALID: 'DISCUSSION_COMMENT_PARENT_INVALID',
  DISCUSSION_FORBIDDEN_COMMENT_AUTHOR: 'DISCUSSION_FORBIDDEN_COMMENT_AUTHOR',

  // Reportes
  REPORT_IMAGE_TYPE_INVALID: 'REPORT_IMAGE_TYPE_INVALID',
  REPORT_TARGET_REQUIRED: 'REPORT_TARGET_REQUIRED',
  REPORT_TARGET_INVALID: 'REPORT_TARGET_INVALID',

  // Storage (S3)
  STORAGE_NOT_CONFIGURED: 'STORAGE_NOT_CONFIGURED',
  STORAGE_PUT_FAILED: 'STORAGE_PUT_FAILED',
  STORAGE_DELETE_FAILED: 'STORAGE_DELETE_FAILED',
} as const;

export type ErrorCodeId = (typeof ErrorCode)[keyof typeof ErrorCode];
